Never haproxy for backend router

diff --git a/ok-haproxy-be/SOURCES/haproxy.init b/ok-haproxy-be/SOURCES/haproxy.init
--- a/ok-haproxy-be/SOURCES/haproxy.init
+++ b/ok-haproxy-be/SOURCES/haproxy.init
@@ -1,41 +1,47 @@
 #!/bin/sh
 #
-# chkconfig: - 85 15
+# chkconfig: - 11 89
 # description: HA-Proxy is a TCP/HTTP reverse proxy which is particularly suited \
 #              for high availability environments.
-# processname: haproxy
-# config: /opt/haproxy/conf/haproxy.cfg
-# pidfile: /var/run/haproxy.pid
+# processname: haproxy-be
+# config:      /opt/haproxy-be/conf/haproxy-be.cfg
+# pidfile:     /var/run/haproxy-be.pid
 
+# Load redhat init script functions
 . /etc/init.d/functions
 
-# This is our service name
-BASENAME=haproxy-be
+#---------------------------------------------------------------------------------------------------
+CONFIG_FILE="/opt/haproxy-be/conf/haproxy-be.cfg"
+PID_FILE="/var/run/haproxy-be.pid"
 
-# Our pid file
-PIDFILE=/var/run/$BASENAME.pid
+# Make sure config file exists
+if ! [ -f $CONFIG_FILE ]; then
+  echo "No config file found! Please make sure $CONFIG_FILE exists!"
+  exit 1
+fi
 
-[ -f /opt/haproxy-be/conf/haproxy-be.cfg ] || exit 1
-
+# Default exit code
 RETVAL=0
 
+#---------------------------------------------------------------------------------------------------
 start() {
-  /opt/haproxy-be/bin/haproxy-be -c -q -f /opt/haproxy-be/conf/haproxy-be.cfg
+  /opt/haproxy-be/bin/haproxy-be -c -q -f $CONFIG_FILE
   if [ $? -ne 0 ]; then
-    echo "Errors found in configuration file, check it with '$BASENAME check'."
+    echo "Errors found in configuration file, check it with 'haproxy-be check'."
     return 1
   fi
 
-  echo -n "Starting $BASENAME: "
-  /opt/haproxy-be/bin/haproxy-be -D -f /opt/haproxy-be/conf/haproxy-be.cfg -p $PIDFILE
+  echo -n "Starting Backend Router Haproxy: "
+  /opt/haproxy-be/bin/haproxy-be -D -f $CONFIG_FILE -p $PID_FILE
   RETVAL=$?
   echo
   return $RETVAL
 }
 
+#---------------------------------------------------------------------------------------------------
 stop() {
-  echo -n "Shutting down $BASENAME: "
-  PID=`cat $PIDFILE`
+  echo -n "Shutting down Backend Router Haproxy: "
+  PID=`cat $PID_FILE`
   if [ "$PID" == "" ]; then
     echo "Not running!"
     return 1
@@ -43,80 +49,74 @@ stop() {
   kill -USR1 $PID
   RETVAL=$?
   echo
-  [ $RETVAL -eq 0 ] && rm -f $PIDFILE
+  [ $RETVAL -eq 0 ] && rm -f $PID_FILE
   return $RETVAL
 }
 
-reload() {
-  /opt/haproxy-be/bin/haproxy-be -c -q -f /opt/haproxy-be/conf/haproxy-be.cfg
-  if [ $? -ne 0 ]; then
-    echo "Errors found in configuration file, check it with '$BASENAME check'."
-    return 1
-  fi
-
-  echo -n "Reloading $BASENAME: "
-  /opt/haproxy-be/bin/haproxy-be -f /opt/haproxy-be/conf/haproxy-be.cfg -p $PIDFILE -sf $(<$PIDFILE)
-  RETVAL=$?
-  echo
-  return $RETVAL
-}
-
+#---------------------------------------------------------------------------------------------------
 restart() {
-  /opt/haproxy-be/bin/haproxy-be -c -q -f /opt/haproxy-be/conf/haproxy-be.cfg
+  /opt/haproxy-be/bin/haproxy-be -c -q -f $CONFIG_FILE
   if [ $? -ne 0 ]; then
-    echo "Errors found in configuration file, check it with '$BASENAME check'."
+    echo "Errors found in configuration file, check it with 'haproxy-be check'."
     return 1
   fi
 
-  echo -n "Restarting $BASENAME: "
-  /opt/haproxy-be/bin/haproxy-be -f /opt/haproxy-be/conf/haproxy-be.cfg -p $PIDFILE -st $(<$PIDFILE)
+  echo -n "Restarting Backend Router Haproxy: "
+  /opt/haproxy-be/bin/haproxy-be -f $CONFIG_FILE -p $PID_FILE -st $(<$PID_FILE)
   RETVAL=$?
   echo
   return $RETVAL
 }
 
+#---------------------------------------------------------------------------------------------------
+reload() {
+  /opt/haproxy-be/bin/haproxy-be -c -q -f $CONFIG_FILE
+  if [ $? -ne 0 ]; then
+    echo "Errors found in configuration file, check it with 'haproxy-be check'."
+    return 1
+  fi
+
+  echo -n "Gracefully restarting Backend Router Haproxy: "
+  /opt/haproxy-be/bin/haproxy-be -f $CONFIG_FILE -p $PID_FILE -sf $(<$PID_FILE)
+  RETVAL=$?
+  echo
+  return $RETVAL
+}
+
+#---------------------------------------------------------------------------------------------------
 check() {
-  /opt/haproxy-be/bin/haproxy-be -c -q -V -f /opt/haproxy-be/conf/haproxy-be.cfg
+  /opt/haproxy-be/bin/haproxy-be -c -q -V -f $CONFIG_FILE
 }
-
-rh_status() {
-    status -p $PIDFILE $BASENAME
-}
-
-rh_status_q() {
-    rh_status >/dev/null 2>&1
-}
-
 
 # See how we were called.
 case "$1" in
   start)
-    rh_status_q && exit 0
     start
     ;;
+
   stop)
-    rh_status_q || exit 0
     stop
     ;;
+
   restart)
     restart
     ;;
-  force-restart)
-    stop
-    start
-    ;;
+
   reload)
     reload
     ;;
+
   check)
     check
     ;;
+
   status)
-    rh_status
+    status -p $PID_FILE haproxy-be
     RETVAL=$?
     ;;
+
   *)
-    echo $"Usage: $BASENAME {start|stop|restart|reload|force-restart|status|check}"
+    echo $"Usage: haproxy-be {start|stop|restart|reload|condrestart|status|check}"
     RETVAL=1
 esac
 
